### ISSUE TITLE
Add instruction or script to run tests?

### ISSUE THREAD

**Issue by flokno** [vidarsko/ComFiT#11]
Hi, I did not find instructions on how to run the tests. I am used to just running `pytest`. Here I have to run all python scripts? 

I would suggest to either add a script that runs all the tests, or simply add instructions (e.g. in the `test` folder)

**Comment by vidarsko** [comment]
Thank you for raising the issue. I have added instructions on how to run the tests in the repository's README.

**Comment by flokno** [comment]
@vidarsko thanks -- I think you mean

```
python -m unittest discover -s ./tests/
```

? At least on Linux/macOS

**Comment by flokno** [comment]
alright, thanks 👍
