### ISSUE TITLE
TypeError in `tutorial/bose_einstein_condensate_basic_framework.ipynb`

### ISSUE THREAD

**Issue by flokno** [vidarsko/ComFiT#15]
When running the `bose_einstein_condensate_basic_framework` tutorial, I get

I get

<img width="1121" alt="image" src="https://github.com/vidarsko/ComFiT/assets/28858706/00ebaab1-c5e6-48b6-8158-7cc9ae978120">

**Comment by vidarsko** [comment]
Thanks. The usage was not correct. the cell should be:

```python
# task 8

J_s = bec.calc_superfluid_current()
H = bec.calc_hamiltonian_density()

fig, ax=bec.plot_field(H,cmap_symmetric=False,colormap = 'cool')
bec.plot_vector_field(J_s, ax=ax)
plt.show()
```

I have updated the tutorial. See if it works for you.

**Comment by flokno** [comment]
confirmed
