### ISSUE TITLE
`TypeError` in `tutorial/bose_einstein_condensate_comoving_frame_and_defect_tracking.ipynb`

### ISSUE THREAD

**Issue by flokno** [vidarsko/ComFiT#16]
When running the solutions in `tutorial/bose_einstein_condensate_comoving_frame_and_defect_tracking.ipynb`, I get

<img width="933" alt="image" src="https://github.com/vidarsko/ComFiT/assets/28858706/14d31479-8b8a-4fc1-99ac-275b72eeca61">

**Comment by vidarsko** [comment]
Yes, the problem is that `ax` should be passed as a keyword argument. It should be 

```python 
#task 4
vel_x = 0.40



N= 800

for n in range(N):
    psi_prev = np.copy(bec.psi)
    
    bec.evolve_comoving_dGPE(10,vel_x,method='ETD4RK')
    
    dt_psi = (bec.psi - psi_prev)/(bec.dt*10)
    nodes = bec.calc_vortex_nodes(dt_psi=dt_psi)

    fig,ax=bec.plot_field(np.abs(bec.psi)**2,cmap_symmetric=False,colormap = 'gray')
    
    bec.plot_vortex_nodes(nodes,ax=ax)
    cf.tool_save_plot(n)

cf.tool_make_animation_gif(n)
```

I have fixed the tutorial and pushed the changes.

**Comment by flokno** [comment]
👍
