### ISSUE TITLE
`TypeError` in `tutorial/bose_einstein_condensate_time_dependenent_potentials.ipynb`

### ISSUE THREAD

**Issue by flokno** [vidarsko/ComFiT#17]
<img width="1072" alt="image" src="https://github.com/vidarsko/ComFiT/assets/28858706/2f6583cd-0a25-47de-ae88-952e0dc569ae">

**Comment by vidarsko** [comment]
Same issue as the ones that were just raised: `ax` needs to be passed as a keyword argument. I have fixed the tutorials and pushed the changes.

**Comment by flokno** [comment]
👍
