### ISSUE TITLE
Some of the functions in nematic_liquid_crystals need better names

### ISSUE THREAD

**Issue by vidarsko** [vidarsko/ComFiT#24]
The names of the functions should be self-explanatory

conf_u in nematic_liquid_crystal needs better name         #TODO: This function needs a more descriptive name (Vidar 03.01.24) #TODO: This function needs a more descriptive name (Vidar 21.01.24) same with calc_grad_p_f

**Comment by jonasron** [comment]
This has now been replaced with

conf_velocity

and

calc_gradient_pressure_f

**Comment by vidarsko** [comment]
Have you replace the names across the project? If so, you may close the issue.
