### ISSUE TITLE
Test fails locally

### ISSUE THREAD

**Issue by carlfre** [vidarsko/ComFiT#43]
Locally, test_calc_determinant fails as follows:

```
  File "/home/carlfre/work/ComFiT/tests/test_base_system.py", line 166, in test_calc_determinant_field
    self.assertAlmostEquals(D[bs.xmidi,bs.ymidi], 1.0)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TestBaseSystem' object has no attribute 'assertAlmostEquals'. Did you mean: 'assertAlmostEqual'?
```

Test passes after replacing 'assertAlmostEquals' with 'assertAlmostEqual'. But I have not committed this yet: the test seem to pass using github actions. Is it fine as-is?

**Comment by jonasron** [comment]
Relevant discussion: https://github.com/python/cpython/issues/53670  It is fine as is, but the standard is to use assertAlmostEqual so you can go ahead and commit the change.
