### ISSUE TITLE
plot_tool_set_axis_properties_matplotlib not imported anywhere

### ISSUE THREAD

**Issue by carlfre** [vidarsko/ComFiT#47]
line 400 in plot_vector_fielt_matplotlib.py: plot_tool_set_axis_properties_matplotlib is not imported/defined anywhere.

Should this be tool_set_plot_axis_properties_matplotlib from  tool/tool_set_plot_axis_properties_matplotlib.py?

There are also two references to a method self.plot_tool_set_axis_properties_matplotlib in the code. Should this also be changed?

**Comment by vidarsko** [comment]
Fixed.
